const words = {

B1:[

{hun:"kutya",eng:"dog"},
{hun:"macska",eng:"cat"},
{hun:"ház",eng:"house"},
{hun:"asztal",eng:"table"},
{hun:"víz",eng:"water"},
{hun:"iskola",eng:"school"},
{hun:"alma",eng:"apple"},
{hun:"barát",eng:"friend"},
{hun:"könyv",eng:"book"},
{hun:"telefon",eng:"phone"},
{hun:"ajtó",eng:"door"},
{hun:"autó",eng:"car"},
{hun:"város",eng:"city"},
{hun:"idő",eng:"time"},
{hun:"ember",eng:"person"},
{hun:"munka",eng:"work"},
{hun:"étel",eng:"food"},
{hun:"pénz",eng:"money"},
{hun:"család",eng:"family"},
{hun:"utazás",eng:"travel"},
{hun:"tanulás",eng:"study"},
{hun:"ablak",eng:"window"},
{hun:"erkély",eng:"balcony"},
{hun:"lámpa",eng:"lamp"},
{hun:"verseny",eng:"competition"},
{hun:"körte",eng:"pear"},
{hun:"hűtőszekrény",eng:"refrigerator"},
{hun:"kert",eng:"garden"},
{hun:"óvoda",eng:"kindergarten"},
{hun:"tervez",eng:"plan"},
{hun:"fejleszt",eng:"develop"},
{hun:"informatika",eng:"informatics"},
{hun:"felfedez",eng:"discover"},
{hun:"feltalál",eng:"invent"},
{hun:"csinál",eng:"make"},
{hun:"torta",eng:"cake"},
{hun:"kapucnis pulcsi",eng:"hoodie"},
{hun:"kabát",eng:"coat"},
{hun:"szoknya",eng:"skirt"},
{hun:"szemüveg",eng:"glasses"},
{hun:"karkötő",eng:"bracelet"},
{hun:"tej",eng:"milk"},
{hun:"séta",eng:"walk"},
{hun:"hörcsög",eng:"hamster"},
{hun:"kő",eng:"stone"},
{hun:"repülő",eng:"airplane"},
{hun:"cipő",eng:"shoe"},
{hun:"számítógép",eng:"computer"},
{hun:"monitor",eng:"monitor"},
{hun:"festés",eng:"painting"},
{hun:"előadás",eng:"presentation"},
{hun:"bevásárlóközpont",eng:"shopping mall"},
{hun:"kosárlabda",eng:"basketball"},
{hun:"sárgadinnye",eng:"melon"}

],

B2:[

{hun:"kapcsolat",eng:"relationship"},
{hun:"megoldás",eng:"solution"},
{hun:"eredmény",eng:"result"},
{hun:"cél",eng:"goal"},
{hun:"siker",eng:"success"},
{hun:"szokás",eng:"habit"},
{hun:"kommunikáció",eng:"communication"},
{hun:"kihívás",eng:"challenge"},
{hun:"különbség",eng:"difference"},
{hun:"környezet",eng:"environment"},
{hun:"csapat",eng:"team"},
{hun:"vita",eng:"debate"},
{hun:"ötlet",eng:"idea"},
{hun:"bolygó",eng:"planet"},
{hun:"trükk",eng:"trick"},
{hun:"szögletes",eng:"square"},
{hun:"tinédzser",eng:"teenager"},
{hun:"idősebb",eng:"older"},
{hun:"eleje",eng:"beginning"},
{hun:"vége",eng:"end"},
{hun:"összeesik",eng:"collapse"},
{hun:"betegség",eng:"illness"},
{hun:"stílus",eng:"style"},
{hun:"elegáns",eng:"elegant"},
{hun:"alagsor",eng:"basement"},
{hun:"rakéta",eng:"rocket"},
{hun:"közlekedési lámpa",eng:"traffic light"},
{hun:"véletlenül",eng:"accidentally"},
{hun:"mindig",eng:"always"},
{hun:"általában",eng:"usually"},
{hun:"középső",eng:"middle"},
{hun:"szkennel",eng:"scan"},
{hun:"biztonság",eng:"security"}

],

C1:[

{hun:"fenntartható",eng:"sustainable"},
{hun:"megbízható",eng:"reliable"},
{hun:"jelentőség",eng:"significance"},
{hun:"alkalmazkodni",eng:"adapt"},
{hun:"megközelítés",eng:"approach"},
{hun:"tudatosság",eng:"awareness"},
{hun:"kifinomult",eng:"sophisticated"},
{hun:"bizonyíték",eng:"evidence"},
{hun:"értelmezés",eng:"interpretation"},
{hun:"hatékony",eng:"efficient"},
{hun:"összefüggés",eng:"correlation"},
{hun:"következtetés",eng:"conclusion"},
{hun:"feltételezés",eng:"assumption"},
{hun:"szemlélet",eng:"perspective"},
{hun:"elemzés",eng:"analysis"},
{hun:"stratégia",eng:"strategy"},
{hun:"koncepció",eng:"concept"},
{hun:"alkalmazkodás",eng:"adaptation"},
{hun:"eredetiség",eng:"originality"},
{hun:"zseni",eng:"genius"},
{hun:"adottság",eng:"ability"},
{hun:"mentalitás",eng:"mentality"},
{hun:"típus",eng:"type"},
{hun:"elegancia",eng:"elegance"},
{hun:"ruhatár",eng:"wardrobe"},
{hun:"felújít",eng:"renovate"},
{hun:"faház",eng:"cabin"},
{hun:"esős",eng:"rainy"},
{hun:"lefelé",eng:"downward"},
{hun:"kiállít",eng:"exhibit"},
{hun:"régész",eng:"archaeologist"},
{hun:"civilizáció",eng:"civilization"},
{hun:"birodalom",eng:"empire"},
{hun:"megfertőz",eng:"infect"},
{hun:"újraindít",eng:"restart"},
{hun:"parancs",eng:"command"},
{hun:"sors",eng:"fate"}

]

}
